<div class="text-center mt-5">
    <p style="font-weight: bold; font-size: 40px">Peminjaman Buku</p>
</div>
<div class="container mt-5">


    <form action="" method="POST">
        @if ($errors->any())
            @foreach ($errors->all() as $error)
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{ $error }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endforeach
        @endif

        @if (session()->has('success'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{ session('success') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif

        @if (session()->has('errorNoBook'))
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{ session('errorNoBook') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif


        <div class="row">
            <div class="col-6">
                @csrf
                <label for="no_pinjam">Nomor Peminjaman</label>
                <input type="text" value="Autogenerated by Computer" readonly disabled class="form-control">
                <br>
                <label for="id_anggota">Nama Anggota <sup class="text-danger">*</sup></label>
                <select class="select2 form-control" name="id_anggota" id="id_anggota" required>
                    <option value="" disabled selected>Cari Anggota</option>
                    @foreach ($anggotas as $anggota)
                        <option value="{{ $anggota->id }}">{{ $anggota->name }}</option>
                    @endforeach

                </select>

                <br>
                <br>
                <label for="tgl_peminjaman">Tanggal Peminjaman <sup class="text-danger">*</sup></label>
                <input type="date" value="{{ $dateNow }}" class="form-control" name="tgl_peminjaman"
                    id="tgl_peminjaman" required>

                <br>
                <label for="tgl_kembali">Tanggal Pengembalian <sup class="text-danger">*</sup></label>
                <input type="date" class="form-control" name="tgl_kembali" id="tgl_kembali" required>

                <br>
                <label for="">Buku Pinjaman <sup class="text-danger">*</sup></label>
                <div class="input-group">

                    <select id="buku_pinjaman" class="select2 form-control mr-3">
                        <option value="" disabled selected>Cari Buku</option>
                        @foreach ($bukus as $buku)
                            <option value="{{ $buku->id }}" kode_buku={{ $buku->kode_buku }}>{{ $buku->judul_buku }}
                            </option>
                        @endforeach
                    </select>
                    <button class="btn-sm btn btn-secondary ml-3" type="button" onclick="addBukuPinjaman()">Tambah
                        Buku</button>

                </div>

                <br>

                <button class="btn btn-primary" type="submit">Simpan Peminjaman</button>



            </div>


        </div>



        <div class="row mt-5">
            <div class="col">
                <div class="card">
                    <div class="card-header"><b>Daftar Buku</b></div>
                    <div class="card-body">
                        <table class="table" id="list_buku_pinjaman" name="list_buku_pinjaman">
                            <thead>
                                <tr>
                                    <th>ID Buku</th>
                                    <th>Kode Buku</th>
                                    <th>Nama Buku</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </form>


</div>
